{
 "title": "Loki Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Log Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Log Event Frequency",
   "type": "gauge",
   "description": "Monitora la frequenza degli eventi di log per vedere se ci sono periodi in cui i log si accumulano rapidamente o rallentano. Calcola la media temporale tra i log. Il numero delle operazioni al secondo.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate({job=~\"gateway|document-store|crm|comunication-manager|analytics\"}[1m]))\r\n"
    }
   ]
  },
  {
   "title": "Log Volume by Service",
   "type": "timeseries",
   "description": "Questo pannello mostra il volume di log raccolti per ciascun servizio nel tempo. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"gateway|document-store|crm|comunication-manager|analytics\"}[1m])) by (job)\r\n"
    }
   ]
  },
  {
   "title": "Log Bandwidth by Service",
   "type": "timeseries",
   "description": "Mostra la quantità di log generati (in termini di byte) per servizio. Può indicare servizi che generano molti log e sovraccaricano il sistema.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate({job=~\"gateway|document-store|crm|comunication-manager|analytics\"}[5m])) by (job)\r\n"
    }
   ]
  },
  {
   "title": "Log Rate by Service Over Time",
   "type": "timeseries",
   "description": "Mostra il tasso di log generati per ciascun servizio nel tempo, utile per monitorare aumenti improvvisi di log che potrebbero indicare problemi.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate({job=~\"gateway|document-store|crm|comunication-manager|analytics\"}[1m])\r\n"
    }
   ]
  },
  {
   "title": "Warning Logs by Service",
   "type": "barchart",
   "description": "Visualizza il numero di log con livello di avviso WARN per ogni servizio negli ultimi 5 minuti. Questo aiuta a tracciare eventi che potrebbero non essere critici ma che potrebbero diventare problemi.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"gateway|document-store|crm|comunication-manager|analytics\"} |= `WARN` [5m])) by (job)\r\n"
    }
   ]
  },
  {
   "title": "Error Logs by Service",
   "type": "barchart",
   "description": "Questo pannello mostra il numero di errori nei log per ciascun servizio. Cerca pattern che corrispondono a errori (es. ERROR o 5xx).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"gateway|document-store|crm|comunication-manager|analytics\"} |= `ERROR` [5m])) by (job)\r\n"
    }
   ]
  },
  {
   "title": "5xx Errors by Service",
   "type": "barchart",
   "description": "Tasso di errori HTTP 5xx nei log dei vari servizi.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "count_over_time({job=~\"gateway|document-store|crm|comunication-manager|analytics\"} |= \"5xx\" [5m])\r\n"
    }
   ]
  },
  {
   "title": "Critical Logs by Service",
   "type": "timeseries",
   "description": "Mostra gli avvisi o log critici come gli errori di sistema o crash. Cerca pattern specifici come \"CRITICAL\" o \"FATAL\".",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "count_over_time({job=~\"gateway|crm|comunication-manager|analytics|document-store\"} |= `CRITICAL` [5m])"
    }
   ]
  },
  {
   "title": "Top Errors by Message",
   "type": "table",
   "description": "Mostra i primi 5 messaggi di errore più frequenti per ogni servizio nelle ultime 24 ore. Questo aiuta a identificare gli errori ricorrenti e le problematiche frequenti.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "topk(5, count_over_time({job=~\"gateway|document-store|crm|comunication-manager|analytics\"} |= `ERROR` [1h])) by (msg)\r\n"
    }
   ]
  },
  { "title": "Log Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Recent Fatal Errors",
   "type": "logs",
   "description": "Mostra gli errori FATAL più recenti in ciascun servizio, utile per individuare rapidamente gli eventi critici.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "{job=~\"gateway|document-store|crm|comunication-manager|analytics\"} |= \"FATAL\"\r\n"
    }
   ]
  },
  {
   "title": "Log for Document-Store",
   "type": "logs",
   "description": "Consente agli utenti di filtrare i log in base ai servizi (job). Questo è utile per un'analisi approfondita di un servizio specifico.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "{job=\"document-store\"} | logfmt"
    }
   ]
  },
  {
   "title": "Log for Crm",
   "type": "logs",
   "description": "Consente agli utenti di filtrare i log in base ai servizi (job). Questo è utile per un'analisi approfondita di un servizio specifico.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "{job=\"crm\"} | logfmt"
    }
   ]
  },
  {
   "title": "Log for Gateway",
   "type": "logs",
   "description": "Consente agli utenti di filtrare i log in base ai servizi (job). Questo è utile per un'analisi approfondita di un servizio specifico.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "{job=\"gateway\"} | logfmt"
    }
   ]
  },
  {
   "title": "Log for Analytics",
   "type": "logs",
   "description": "Consente agli utenti di filtrare i log in base ai servizi (job). Questo è utile per un'analisi approfondita di un servizio specifico.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "{job=\"analytics\"} | logfmt"
    }
   ]
  },
  {
   "title": "Log for Comunication-Manager",
   "type": "logs",
   "description": "Consente agli utenti di filtrare i log in base ai servizi (job). Questo è utile per un'analisi approfondita di un servizio specifico.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "{job=\"comunication-manager\"} | logfmt"
    }
   ]
  }
 ]
}