{
 "title": "Prometheus Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Server Requets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Requests Seconds Count",
   "type": "timeseries",
   "description": "Conta totale delle richieste al server per microservizio. Questa metrica è utile per capire il volume di traffico che ciascun servizio sta gestendo.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"document-store|crm|comunication-manager|analytics\"}[1m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total API Errors by Microservice (4..|5..)",
   "type": "barchart",
   "description": "Conta totale degli errori API per microservizio, considerando gli errori client (4xx) e server (5xx). Serve per identificare quanti errori si stanno verificando, utili per diagnosticare problemi.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"document-store|crm|comunication-manager|analytics\", status=~\"4..|5..\"}[1m])) by (job)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Error Rate by Microservice (4..)",
   "type": "gauge",
   "description": "Tasso di errore delle API per microservizio, considerando solo gli errori client (4xx). Aiuta a capire se gli utenti stanno facendo richieste errate o se ci sono problemi nell'input.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (rate(http_server_requests_seconds_count{job=~\"document-store|crm|comunication-manager|analytics\", status=~\"4..\"}[1m])) / sum by(job) (rate(http_server_requests_seconds_count{job=~\"document-store|crm|comunication-manager|analytics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per HTTP Method by Microservice",
   "type": "timeseries",
   "description": "Numero di richieste per tipo di metodo HTTP (GET, POST, PUT, DELETE) per ciascun microservizio. Aiuta a monitorare il bilanciamento del traffico tra i diversi tipi di operazioni.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"document-store|crm|comunication-manager|analytics\", method=~\"GET|POST|PUT|DELETE\"}[1m])) by (method, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Success Rate by Microservice",
   "type": "gauge",
   "description": "Percentuale di richieste API che hanno avuto successo (status 2xx). Una metrica fondamentale per misurare l'efficacia dei microservizi nel rispondere correttamente alle richieste.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"document-store|crm|comunication-manager|analytics\", status=~\"2..\"}[1m])) by (job)\r\n/\r\nsum(rate(http_server_requests_seconds_count{job=~\"document-store|crm|comunication-manager|analytics\"}[1m])) by (job)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time by Microservice",
   "type": "timeseries",
   "description": "    Tempo di risposta medio delle API per ciascun microservizio. Utile per valutare le performance e identificare eventuali rallentamenti nelle risposte ai client.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=~\"document-store|crm|comunication-manager|analytics\"}[1m])) by (job)\r\n/\r\nsum(rate(http_server_requests_seconds_count{job=~\"document-store|crm|comunication-manager|analytics\"}[1m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Usage by Microservice",
   "type": "timeseries",
   "description": "Utilizzo della CPU per ciascun microservizio. Misura l’efficienza dell’uso delle risorse di calcolo e può aiutare a prevenire problemi di prestazioni legati al sovraccarico della CPU.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(process_cpu_usage{job=~\"document-store|crm|comunication-manager|analytics\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Microservice (heap)",
   "type": "timeseries",
   "description": "Quantità di memoria heap utilizzata dal microservizio. L’heap è dove le applicazioni Java allocano la memoria dinamica, e un suo monitoraggio aiuta a prevenire problemi di memoria (out of memory).",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=~\"document-store|crm|comunication-manager|analytics\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Microservice (nonheap)",
   "type": "timeseries",
   "description": "Utilizzo della memoria non-heap per ciascun microservizio. Comprende aree come il class loader e le strutture JVM. Utile per diagnosticare problemi di memoria oltre l'heap principale.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=~\"document-store|crm|comunication-manager|analytics\", area=\"nonheap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Threads by Microservice",
   "type": "timeseries",
   "description": "Numero di thread attivi per ciascun microservizio. Serve a monitorare l’uso della concorrenza nel sistema e può indicare problemi se il numero di thread diventa troppo elevato.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=~\"document-store|crm|comunication-manager|analytics\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Usage by Microservice (Java)",
   "type": "timeseries",
   "description": "Percentuale di utilizzo della CPU da parte dei microservizi Java. Monitorare questa metrica aiuta a rilevare problemi di prestazioni legati al sovraccarico della CPU del sistema.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "system_cpu_usage{job=~\"document-store|crm|comunication-manager|analytics\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "gauge",
   "description": "Verifica la disponibilità dei microservizi, mostrando se sono attivi o meno. È una metrica critica per il monitoraggio della salute generale del sistema.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"document-store|crm|comunication-manager|analytics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}