spring:
  application:
    name: document_store

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    problemdetails:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/job-connect

server:
  port: 8081

#logging:level:org:springframework:web=DEBUG