spring:
  application:
    name: document_store

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    problemdetails:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/job-connect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  file:
    path: ./../logs/document-store
  level:
    root: INFO
    org.springframework.web: DEBUG

server:
  port: 8081