export const testCustomers = [
  {
    name: "John",
    surname: "Doe",
    ssnCode: "JHNDOE1234",
    category: "CUSTOMER",
    comment: "Frequent customer with special discounts.",
    emailDTOs: [{ email: "john.doe@example.com", comment: "Primary email" }],
    telephoneDTOs: [{ telephone: "+11234567890", comment: "Main phone number" }],
    addressDTOs: [{ state: "California", region: "West", city: "Los Angeles", address: "123 Sunset Blvd", comment: "Home address" }],
  },
  {
    name: "Jane",
    surname: "Smith",
    ssnCode: "JANSMT5678",
    category: "CUSTOMER",
    comment: "Occasional customer.",
    emailDTOs: [{ email: "jane.smith@example.com", comment: "Work email" }],
    telephoneDTOs: [{ telephone: "+442071234567", comment: "Office phone" }],
    addressDTOs: [{ state: "New York", region: "East", city: "New York", address: "456 Broadway", comment: "Business address" }],
  },
  {
    name: "Robert",
    surname: "Johnson",
    ssnCode: "RBRTJHN9012",
    category: "CUSTOMER",
    comment: "High-value customer with personalized services.",
    emailDTOs: [{ email: "robert.johnson@vipmail.com", comment: "VIP email" }],
    telephoneDTOs: [
      { telephone: "3312345678", comment: "Private phone" },
      { telephone: "3321234567", comment: "Backup phone" },
    ],
    addressDTOs: [{ state: "Florida", region: "South", city: "Miami", address: "789 Ocean Drive", comment: "Vacation home" }],
  },
  {
    name: "Emily",
    surname: "Clark",
    ssnCode: "EMLCLK3456",
    category: "CUSTOMER",
    comment: "New customer, just signed up.",
    emailDTOs: [
      { email: "emily.clark@example.com", comment: "Personal email" },
      { email: "emily.clark@workmail.com", comment: "Work email" },
    ],
    telephoneDTOs: [{ telephone: "6129876543", comment: "Mobile phone" }],
    addressDTOs: [{ state: "Texas", region: "Central", city: "Houston", address: "1010 Main St", comment: "Residential address" }],
  },
  {
    name: "Michael",
    surname: "Brown",
    ssnCode: "MICBRN7890",
    category: "CUSTOMER",
    comment: "Customer interested in tech products.",
    emailDTOs: [],
    telephoneDTOs: [{ telephone: "+49301234567", comment: "Work phone" }],
    addressDTOs: [{ state: "Bavaria", region: "South", city: "Munich", address: "123 Tech Avenue", comment: "Office address" }],
  },
  {
    name: "Sophia",
    surname: "Taylor",
    ssnCode: "SOPTAY1234",
    category: "CUSTOMER",
    comment: "Loyal customer with luxury preferences.",
    emailDTOs: [{ email: "sophia.taylor@luxurymail.com", comment: "Luxury customer email" }],
    telephoneDTOs: [],
    addressDTOs: [{ state: "Zurich", region: "Central", city: "Zurich", address: "15 Bahnhofstrasse", comment: "Apartment address" }],
  },
  {
    name: "Liam",
    surname: "Wilson",
    ssnCode: "LIAWLS2345",
    category: "CUSTOMER",
    comment: "Frequent shopper in the electronics category.",
    emailDTOs: [{ email: "liam.wilson@shoppermail.com", comment: "Shopper email" }],
    telephoneDTOs: [{ telephone: "6569876543", comment: "Mobile phone" }],
    addressDTOs: [{ state: "Singapore", region: "East", city: "Singapore", address: "88 Orchard Rd", comment: "Residential address" }],
  },
  {
    name: "Ava",
    surname: "Martinez",
    ssnCode: "AVAMRT5678",
    category: "CUSTOMER",
    comment: "Recently became a customer.",
    emailDTOs: [],
    telephoneDTOs: [{ telephone: "+34911234567", comment: "Office phone" }],
    addressDTOs: [{ state: "Madrid", region: "Central", city: "Madrid", address: "456 Gran Via", comment: "Office address" }],
  },
  {
    name: "William",
    surname: "Garcia",
    ssnCode: "WLMGRN6789",
    category: "CUSTOMER",
    comment: "Customer with high interaction history.",
    emailDTOs: [
      { email: "william.garcia@premiumcustomer.com", comment: "Premium customer email" },
      { email: "w.garcia@personalmail.com", comment: "Personal email" },
    ],
    telephoneDTOs: [],
    addressDTOs: [{ state: "Mexico City", region: "Central", city: "Mexico City", address: "789 Reforma Ave", comment: "Business address" }],
  },
  {
    name: "Isabella",
    surname: "Davis",
    ssnCode: "ISBDVS9012",
    category: "CUSTOMER",
    comment: "Customer with exclusive services.",
    emailDTOs: [],
    telephoneDTOs: [{ telephone: "8229876543", comment: "Private phone" }],
    addressDTOs: [{ state: "Seoul", region: "East", city: "Seoul", address: "101 Gangnam St", comment: "Luxury apartment" }],
  },
];
