export const testJobOffers = [
  {
    name: "Software Engineer",
    description: "Development of web applications.",
    contractType: "Full Time",
    location: "New York",
    workMode: "Remote",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["JavaScript", "React", "Node.js"],
    duration: 12,
    value: 60000,
    note: "Looking for a quick hire.",
    customerId: 1,
    candidateProfessionalIds: [],
  },
  {
    name: "Data Analyst",
    description: "Data analysis for business intelligence.",
    contractType: "Part Time",
    location: "London",
    workMode: "Hybrid",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["SQL", "Python", "Tableau"],
    duration: 6,
    value: 30000,
    note: "Expert in data visualization required.",
    customerId: 2,
    candidateProfessionalIds: [],
  },
  {
    name: "Project Manager",
    description: "Manage large-scale IT projects.",
    contractType: "Contract",
    location: "Berlin",
    workMode: "In-Person",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Agile", "Scrum", "Leadership"],
    duration: 18,
    value: 100000,
    note: "PMP certification preferred.",
    customerId: 3,
    candidateProfessionalIds: [],
  },
  {
    name: "UX/UI Designer",
    description: "Design user-friendly interfaces.",
    contractType: "Freelance",
    location: "Paris",
    workMode: "Remote",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Figma", "Sketch", "Wireframing"],
    duration: 3,
    value: 15000,
    note: "Portfolio required.",
    customerId: 4,
    candidateProfessionalIds: [],
  },
  {
    name: "Backend Developer",
    description: "API development and server-side logic.",
    contractType: "Full Time",
    location: "San Francisco",
    workMode: "Hybrid",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Node.js", "SQL", "AWS"],
    duration: 24,
    value: 120000,
    note: "Experience with cloud infrastructure is a plus.",
    customerId: 5,
    candidateProfessionalIds: [],
  },
  {
    name: "Mobile Developer",
    description: "Develop native mobile applications.",
    contractType: "Freelance",
    location: "Tokyo",
    workMode: "In-Person",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Swift", "Kotlin", "React Native"],
    duration: 6,
    value: 80000,
    note: "Experience with cross-platform development is required.",
    customerId: 6,
    candidateProfessionalIds: [],
  },
  {
    name: "DevOps Engineer",
    description: "Maintain and improve CI/CD pipelines.",
    contractType: "Contract",
    location: "Sydney",
    workMode: "Hybrid",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Docker", "Kubernetes", "AWS"],
    duration: 9,
    value: 90000,
    note: "Knowledge of cloud systems is required.",
    customerId: 7,
    candidateProfessionalIds: [],
  },
  {
    name: "Cybersecurity Specialist",
    description: "Ensure system security and protection from threats.",
    contractType: "Full Time",
    location: "Toronto",
    workMode: "Remote",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Firewall", "Penetration Testing", "Network Security"],
    duration: 36,
    value: 130000,
    note: "Experience in ethical hacking preferred.",
    customerId: 8,
    candidateProfessionalIds: [],
  },
  {
    name: "AI Engineer",
    description: "Develop and implement AI-based solutions.",
    contractType: "Part Time",
    location: "Tel Aviv",
    workMode: "Remote",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["TensorFlow", "Python", "Machine Learning"],
    duration: 12,
    value: 70000,
    note: "Strong knowledge of AI algorithms is required.",
    customerId: 9,
    candidateProfessionalIds: [],
  },
  {
    name: "Frontend Developer",
    description: "Build interactive and dynamic web interfaces.",
    contractType: "Freelance",
    location: "Rome",
    workMode: "Hybrid",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["JavaScript", "Vue.js", "CSS"],
    duration: 6,
    value: 40000,
    note: "Experience with modern JS frameworks is preferred.",
    customerId: 10,
    candidateProfessionalIds: [],
  },
  {
    name: "Database Administrator",
    description: "Manage and maintain the company's databases.",
    contractType: "Full Time",
    location: "Amsterdam",
    workMode: "In-Person",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["SQL", "Database Management", "Oracle"],
    duration: 24,
    value: 90000,
    note: "Oracle certification is preferred.",
    customerId: 1,
    candidateProfessionalIds: [],
  },
  {
    name: "Cloud Architect",
    description: "Design and implement cloud solutions.",
    contractType: "Contract",
    location: "Dublin",
    workMode: "Remote",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["AWS", "Azure", "Cloud Architecture"],
    duration: 18,
    value: 150000,
    note: "Expertise in AWS and Azure is essential.",
    customerId: 2,
    candidateProfessionalIds: [],
  },
  {
    name: "HR Manager",
    description: "Oversee recruitment and human resources processes.",
    contractType: "Part Time",
    location: "Madrid",
    workMode: "In-Person",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Recruitment", "Employee Relations", "HR Policies"],
    duration: 6,
    value: 50000,
    note: "Experience in IT industry HR is a plus.",
    customerId: 3,
    candidateProfessionalIds: [],
  },
  {
    name: "Marketing Specialist",
    description: "Plan and execute marketing strategies.",
    contractType: "Freelance",
    location: "Los Angeles",
    workMode: "Hybrid",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["SEO", "Content Marketing", "Social Media"],
    duration: 3,
    value: 25000,
    note: "Experience with digital marketing campaigns is required.",
    customerId: 4,
    candidateProfessionalIds: [],
  },
  {
    name: "Graphic Designer",
    description: "Create visuals for print and digital media.",
    contractType: "Part Time",
    location: "Lisbon",
    workMode: "Remote",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Photoshop", "Illustrator", "InDesign"],
    duration: 6,
    value: 20000,
    note: "Portfolio of previous work is required.",
    customerId: 5,
    candidateProfessionalIds: [],
  },
  {
    name: "QA Engineer",
    description: "Test and ensure the quality of software products.",
    contractType: "Full Time",
    location: "Stockholm",
    workMode: "In-Person",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Selenium", "JIRA", "Manual Testing"],
    duration: 12,
    value: 70000,
    note: "Experience with automated testing tools is required.",
    customerId: 6,
    candidateProfessionalIds: [],
  },
  {
    name: "Content Writer",
    description: "Produce engaging and informative content for various platforms.",
    contractType: "Freelance",
    location: "Vancouver",
    workMode: "Remote",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Writing", "SEO", "Editing"],
    duration: 3,
    value: 15000,
    note: "Samples of previous content are required.",
    customerId: 7,
    candidateProfessionalIds: [],
  },
  {
    name: "Sales Manager",
    description: "Drive sales and manage client relationships with a focus on high-value accounts.",
    contractType: "Contract",
    location: "Singapore",
    workMode: "Hybrid",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Sales Strategy", "CRM", "Negotiation"],
    duration: 12,
    value: 80000,
    note: "Experience with international sales is a plus.",
    customerId: 8,
    candidateProfessionalIds: [],
  },
  {
    name: "Business Analyst",
    description: "Analyze business needs and processes, providing actionable insights.",
    contractType: "Part Time",
    location: "Hong Kong",
    workMode: "Remote",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Business Analysis", "Data Analysis", "Requirements Gathering"],
    duration: 9,
    value: 35000,
    note: "Experience in financial services is preferred.",
    customerId: 9,
    candidateProfessionalIds: [],
  },
  {
    name: "System Administrator",
    description: "Maintain and troubleshoot system infrastructure to ensure optimal performance.",
    contractType: "Full Time",
    location: "Chicago",
    workMode: "In-Person",
    oldStatus: "CREATED",
    status: "CREATED",
    requiredSkills: ["Linux", "Networking", "System Monitoring"],
    duration: 24,
    value: 75000,
    note: "Experience with large-scale systems and network security is required.",
    customerId: 10,
    candidateProfessionalIds: [],
  },
];
