spring:
  application:
    name: comunication_manager
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/job-connect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

gmail-account:
  application_name: comunication-manager-project

gmail:
  client-email: groupg04.polito@gmail.com
  client-id: 535682431083-4kepur0t0uld14g3c0getmkkc6h0o3nd.apps.googleusercontent.com
  client-secret: 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
  refresh-token: 1//04gJR5hNxpw1FCgYIARAAGAQSNwF-L9IrE2Xc025sc_dqJ4N_nvgc1LmOFM_F3vWN4FW62xeLCcopOka2pxUnEU3aGJvCYKNlrTk

camel:
  component:
    google-mail-stream:
      application-name: ${gmail-account.application_name}
      client-id: ${gmail.client-id}
      client-secret: ${gmail.client-secret}
      refresh-token: ${gmail.refresh-token}
    google-mail:
      application-name: ${gmail-account.application_name}
      client-id: ${gmail.client-id}
      client-secret: ${gmail.client-secret}
      refresh-token: ${gmail.refresh-token}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  file:
    path: ./../logs/comunication-manager
  level:
    root: INFO
    org.springframework.web: DEBUG

server:
  port: 8083
  main:
    port: 8080
  crm:
    id: crmService