spring:
  application:
    name: comunication_manager
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/lab5-g04

gmail-account:
  application_name: comunication-manager-project

gmail:
  client-email: groupg04.polito@gmail.com
  client-id: 535682431083-4kepur0t0uld14g3c0getmkkc6h0o3nd.apps.googleusercontent.com
  client-secret: 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
  refresh-token: 1//04vlDTb-yHmwBCgYIARAAGAQSNwF-L9IrusR8MChWxbM_9-0Z6-RHLVShkfsP5vV1ra_Ys3U7mQkQ7e4iyFMtQP95px0AfO5HZxU

camel:
  component:
    google-mail-stream:
      application-name: ${gmail-account.application_name}
      client-id: ${gmail.client-id}
      client-secret: ${gmail.client-secret}
      refresh-token: ${gmail.refresh-token}
    google-mail:
      application-name: ${gmail-account.application_name}
      client-id: ${gmail.client-id}
      client-secret: ${gmail.client-secret}
      refresh-token: ${gmail.refresh-token}

server:
  port: 8083
  main:
    port: 8080
  crm:
    id: crmService