spring:
  application:
    name: crm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cm-to-crm-email-message-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mvc:
    problemdetails:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/job-connect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  file:
    path: ./../logs/crm
  level:
    root: INFO
    org.springframework.web: DEBUG

api:
  ai21:
    url: "https://api.ai21.com/studio/v1/chat/completions"
    key: "Bearer e1as3WOyj3E8GBp0lSBKey8UOo5CNyJL"
    model: "jamba-1.5-large"

org:
  owasp:
    esapi:
      resources: src/main/resources

server:
  port: 8082